# Generated by Django 5.2.6 on 2025-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnailUrl',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/korall/'),
        ),
    ]
